"""empty message

Revision ID: 454e3ac2c624
Revises: 083bcd838215
Create Date: 2024-11-13 22:26:20.649705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '454e3ac2c624'
down_revision = '083bcd838215'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'1'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'1'"))

    # ### end Alembic commands ###
